name: Code Coverage

on:
  pull_request:
    branches: [dev]
  workflow_dispatch:

jobs:
  coverage:
    uses: OpenVoiceOS/gh-automations/.github/workflows/coverage.yml@dev
    with:
      python_version: '3.11'
      coverage_source: 'ovos_messagebus_chat_plugin'
      test_path: 'tests/'
      pre_install_pip: 'ovos-plugin-manager>=2.4.0a1'
      install_extras: '.[test]'
      min_coverage: 0
